### ISSUE TITLE
KUBE_PING on AWS EKS not working...

### ISSUE THREAD

**Issue by bramalingam81** [jgroups-extras/jgroups-kubernetes#146]
I am trying to deploy Infinispan cluster with Jgroups clustering using below mentioned configuration on AWS EKS cluster. When I start the container without the transport config in infinspan.xml, container starts without clustering. When I start the container with transport, container terminates during startup. 

container-logs
```
2022-03-26 16:09:04,088 WARN  (main) [org.infinispan.PERSISTENCE] ISPN000554: jboss-marshalling is deprecated and planned for removal
2022-03-26 16:09:04,435 INFO  (main) [org.infinispan.CONTAINER] ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.5.Final
2022-03-26 16:09:04,669 INFO  (main) [org.infinispan.CLUSTER] ISPN000078: Starting JGroups channel `ISPN` with stack `custom`
2022-03-26 16:09:04,684 WARN  (main) [org.infinispan.commons.util.StringPropertyReplacer] ISPN000901: Property JGROUPS_EXTERNAL_ADDR could not be replaced as intended!
2022-03-26 16:09:04,710 WARN  (main) [org.infinispan.CONTAINER] ISPN000574: Global state cannot persisted because it is incomplete (usually caused by errors at startup).
2022-03-26 16:09:04,847 INFO  (main) [org.infinispan.server.core.RequestTracer] OpenTracing integration is disabled
```

jgroups.xml
```
<TCP external_addr="${JGROUPS_EXTERNAL_ADDR:match-interface:eth0}" bind_addr="site_local,match-interface:eth0" bind_port="${TCP_PORT:7800}" port_range="0" recv_buf_size="5M" send_buf_size="1M" max_bundle_size="64K" enable_diagnostics="true" thread_naming_pattern="cl" sock_conn_timeout="300" thread_pool.min_threads="0" thread_pool.max_threads="500" thread_pool.keep_alive_time="30000" />
<**org.jgroups.protocols.kubernetes.KUBE_PING** port_range="0" namespace="${KUBERNETES_NAMESPACE:kc}" labels="${KUBERNETES_LABELS:app=ispn}" />
```
infinispan.xml
```
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:infinispan:config:13.0" xsi:schemaLocation="urn:infinispan:config:13.0 https://infinispan.org/schemas/infinispan-config-13.0.xsd urn:infinispan:server:13.0 https://infinispan.org/schemas/infinispan-server-13.0.xsd">

    <!-- TODO configure JGROUPS tcp Stack with encryption -->

    <!-- see https://docs.jboss.org/infinispan/13.0/configdocs/infinispan-config-13.0.html -->
    <jgroups>
        <!-- Allows custom jgroups configuration -->
        <stack-file path="/opt/infinispan/server/conf/jgroups-dnsping.xml" name="custom"/>
    </jgroups>

    <cache-container name="default" statistics="true">
        <transport stack="custom" />
  .....
```

Service account and cluster roles

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-kubeping-service-account
  namespace: kc
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-pod-reader
  namespace: kc  
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jgroups-kubeping-api-access
  namespace: kc  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: jgroups-kubeping-service-account
  namespace: kc

```

ispn-deploy.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: ispn
  namespace: kc
  labels:
    app: ispn  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ispn
  template:
    metadata:
      labels:
        app: ispn
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
      - name: ispn
        # TODO: Dynamic ECR host
        image: 233334343.dkr.ecr.us-east-1.amazonaws.com/ispn:latest
        # image: quay.io/keycloak/keycloak:17.0.0      
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace        
        - name: USER
          value: "admin"
        - name: PASS
          value: "admin"
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: kubernetes.KUBE_PING          
        - name: DNS_QUERY
          value: "jgrp.kc.svc.cluster.local"
        - name: DNS_RECORD_TYPE
          value: A          
        # - name: DNS_ADDRESS
        #   value: 172.20.0.10   
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms512m -Djava.net.preferIPv4Stack=true"
        - name: KUBE_NAMESPACE
          value: "kc"                 
        - name: JAVA_OPTS_APPEND
          value: "-Dinfinispan.cluster.stack=kubernetes"
        ports:
        - name: http
          containerPort: 11211
        - name: https
          containerPort: 11222        
        readinessProbe:
          httpGet:
            path: /rest/v2/cache-managers/default/health/status
            port: 11222
          failureThreshold: 5
          initialDelaySeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /rest/v2/cache-managers/default/health/status
            port: 11222
          failureThreshold: 5
          initialDelaySeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: ispn
  labels:
    app: ispn
spec:
  ports:
  - name: http
    port: 11222
    targetPort: 11222
  selector:
    app: ispn
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
#  annotations:
#    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: jgrp
  labels:
    app: ispn
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: ping
      port: 7800
      protocol: TCP
      targetPort: 7800
  selector:
     app: ispn
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
```

Please suggest if there is any specific configuration that are specific to AWS EKS.
