### ISSUE TITLE
Unable to discover members to form a cluster in kubernetes

### ISSUE THREAD

**Issue by kunal-bhatia** [jgroups-extras/jgroups-kubernetes#67]
This is in reference of using ehcache jgroups replication with jgroups library for kubernetes, with which it is unable to find the members with specific namespace to form a cluster, not sure if the match interface is correct or missing some variable to be used in  the configuration

**Dependencies version**
```
<dependency>
			<groupId>org.jgroups</groupId>
			<artifactId>jgroups</artifactId>
			<version>3.6.17.Final</version>
		</dependency>
		<dependency>
			<groupId>org.jgroups.kubernetes</groupId>
			<artifactId>kubernetes</artifactId>
			<version>0.9.3</version>
		</dependency>
		<dependency>
			<groupId>io.undertow</groupId>
			<artifactId>undertow-servlet</artifactId>
			<version>1.3.15.Final</version>
		</dependency>
```
**tcp.xml**
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:org:jgroups"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    <TCP
            bind_addr="${jgroups.tcp.address:match-interface:en.*}"
            bind_port="7800"
            recv_buf_size="5M"
            send_buf_size="1M"
            max_bundle_size="64K"
            enable_diagnostics="true"
            thread_naming_pattern="cl"

            thread_pool.min_threads="0"
            thread_pool.max_threads="500"
            thread_pool.keep_alive_time="30000" />

    <org.jgroups.protocols.kubernetes.KUBE_PING
            namespace="${KUBE_NAMESPACE:ehcache-demo}"/>

    <MERGE3 max_interval="30000"
            min_interval="10000"/>

    <VERIFY_SUSPECT timeout="1500"/>

    <BARRIER />
    <pbcast.NAKACK2 xmit_interval="500"
                    xmit_table_num_rows="100"
                    xmit_table_msgs_per_row="2000"
                    xmit_table_max_compaction_time="30000"
                    use_mcast_xmit="false"
                    discard_delivered_msgs="true" />
    <UNICAST3
            xmit_table_num_rows="100"
            xmit_table_msgs_per_row="1000"
            xmit_table_max_compaction_time="30000"/>
    <pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
                   max_bytes="8m"/>
    <pbcast.GMS print_local_addr="true" join_timeout="3000"
                view_bundling="true"/>
    <MFC max_credits="2M"
         min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <pbcast.STATE_TRANSFER  />
    <CENTRAL_LOCK />
    <COUNTER/>
</config>
```

**K8s Manifests**
```
apiVersion: v1
kind: Namespace
metadata:
  name: ehcache-demo
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ehcache-demo
  namespace: ehcache-demo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ehcache-demo
  namespace: ehcache-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ehcache-demo
  namespace: ehcache-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ehcache-demo
subjects:
- kind: ServiceAccount
  name: ehcache-demo
  namespace: ehcache-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ehcache-demo
  name: ehcache-demo
  namespace: ehcache-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ehcache-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: ehcache-demo
    spec:
      serviceAccountName: ehcache-demo
      containers:
      - image: <some_repo>/ehcache-demo:1.0.10
        name: ehcache-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ehcache-demo
  name: ehcache-demo
  namespace: ehcache-demo
spec:
  ports:
  - name: 5678-8080
    port: 5678
    protocol: TCP
    targetPort: 8080
  selector:
    app: ehcache-demo
  type: NodePort
```

**Logs from the pods (refer to my_view)**
```
07:02:50.012 [main] DEBUG n.s.e.d.j.JGroupsBootstrapCacheLoaderFactory - Creating JGroups BootstrapCacheLoader with configuration:
ehcache-demo-cb44bbf88-nvg4w ehcache-demo {bootstrapAsynchronously=false}
ehcache-demo-cb44bbf88-nvg4w ehcache-demo
ehcache-demo-cb44bbf88-nvg4w ehcache-demo -------------------------------------------------------------------
ehcache-demo-cb44bbf88-nvg4w ehcache-demo GMS: address=ehcache-demo-cb44bbf88-nvg4w-32543, cluster=EH_CACHE, physical address=fe80:0:0:0:b8e9:70ff:fedb:9c30%eth0:7800
ehcache-demo-cb44bbf88-nvg4w ehcache-demo -------------------------------------------------------------------
ehcache-demo-cb44bbf88-nvg4w ehcache-demo 07:02:51.485 [main] DEBUG org.jgroups.ping.kube.Client - getPods(ehcache-demo, null) = [Pod[podIP=100.96.16.64, containers=[]], Pod[podIP=100.96.6.51, containers=[]]]
ehcache-demo-cb44bbf88-nvg4w ehcache-demo 07:02:54.507 [main] INFO  n.s.e.d.j.JGroupsCacheManagerPeerProvider - JGroups Replication started for 'EH_CACHE'. JChannel: local_addr=ehcache-demo-cb44bbf88-nvg4w-32543
ehcache-demo-cb44bbf88-nvg4w ehcache-demo cluster_name=EH_CACHE
ehcache-demo-cb44bbf88-nvg4w ehcache-demo my_view=[ehcache-demo-cb44bbf88-nvg4w-32543|0] (1) [ehcache-demo-cb44bbf88-nvg4w-32543]
ehcache-demo-cb44bbf88-nvg4w ehcache-demo state=CONNECTED
ehcache-demo-cb44bbf88-nvg4w ehcache-demo discard_own_messages=true
ehcache-demo-cb44bbf88-nvg4w ehcache-demo state_transfer_supported=true
ehcache-demo-cb44bbf88-nvg4w ehcache-demo props=TCP(discard_incompatible_packets=true;internal_thread_pool_min_threads=2;internal_thread_pool_keep_alive_time=30000;time_service_interval=500;thread_pool_max_threads=500;internal_thread_pool_queue_enabled=true;ergonomics=true;enable_unicast_bundling=true;port_range=50;conn_expire_time=0;recv_buf_size=5000000;loopback_copy=false;thread_naming_pattern=cl;internal_thread_pool_rejection_policy=abort;internal_thread_pool_enabled=true;send_buf_size=1000000;tcp_nodelay=true;stats=true;oob_thread_pool_enabled=true;oob_thread_pool_rejection_policy=abort;suppress_time_different_version_warnings=60000;id=75;thread_pool_rejection_policy=abort;logical_addr_cache_max_size=2000;suppress_time_different_cluster_warnings=60000;use_send_queues=false;loopback=true;timer_rejection_policy=abort;sock_conn_timeout=2000;oob_thread_pool_min_threads=2;client_bind_port=0;bundler_num_spins=40;send_queue_size=2000;max_bundle_timeout=20;enable_diagnostics=true;internal_thread_pool_max_threads=4;external_port=0;oob_thread_pool_max_threads=10;no_bundler_pool_size=10;log_discard_msgs=true;name=TCP;oob_thread_pool_keep_alive_time=30000;bind_addr=fe80:0:0:0:b8e9:70ff:fedb:9c30%eth0;wheel_size=200;bundler_capacity=16384;log_discard_msgs_version=true;defer_client_bind_addr=false;enable_batching=true;tick_time=50;timer_max_threads=4;thread_pool_queue_enabled=true;enable_bundling=true;oob_thread_pool_queue_enabled=false;thread_pool_keep_alive_time=30000;bind_port=7800;thread_pool_min_threads=0;ignore_dont_bundle=true;reaper_interval=0;bind_interface_str=;diagnostics_ttl=8;loopback_separate_thread=true;logical_addr_cache_expiration=120000;peer_addr_read_timeout=1000;oob_thread_pool_queue_max_size=500;linger=-1;diagnostics_addr=ff0e:0:0:0:0:0:75:75;receive_on_all_interfaces=false;internal_thread_pool_queue_max_size=500;timer_queue_max_size=500;thread_pool_queue_max_size=10000;no_bundler_initial_buf_size=512;max_bundle_size=64000;physical_addr_max_fetch_attempts=1;timer_min_threads=2;thread_pool_enabled=true;bundler_type=transfer-queue;timer_keep_alive_time=5000;logical_addr_cache_reaper_interval=60000;timer_type=new3;diagnostics_port=7500;who_has_cache_timeout=2000)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :kubernetes.KUBE_PING(async_discovery_use_separate_thread_per_request=false;ergonomics=true;serverPort=8888;saTokenFile=/var/run/secrets/kubernetes.io/serviceaccount/token;timeout=3000;send_cache_on_join=false;apiVersion=v1;num_initial_srv_members=0;break_on_coord_rsp=true;stats=true;use_disk_cache=false;connectTimeout=5000;num_initial_members=10;operationSleep=1000;caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt;discovery_rsp_expiry_time=60000;id=2011;stagger_timeout=0;force_sending_discovery_rsps=true;async_discovery=false;clientKeyAlgo=RSA;masterPort=0;always_send_physical_addr_with_discovery_request=true;max_members_in_discovery_request=500;readTimeout=30000;namespace=ehcache-demo;name=KUBE_PING;return_entire_cache=false;operationAttempts=3)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :MERGE3(check_interval=48000;stats=true;min_interval=10000;ergonomics=true;name=MERGE3;id=54;max_participants_in_merge=100;max_interval=30000;only_coords_run_consistency_checker=false)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :VERIFY_SUSPECT(num_msgs=1;use_mcast_rsps=false;bind_interface_str=;stats=true;ergonomics=true;name=VERIFY_SUSPECT;bind_addr=fe80:0:0:0:b8e9:70ff:fedb:9c30%eth0;id=13;timeout=1500;use_icmp=false)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :BARRIER(flush_timeout=5000;stats=true;ergonomics=true;max_close_time=60000;name=BARRIER;id=0)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :pbcast.NAKACK2(resend_last_seqno_max_times=1;use_mcast_xmit=false;ergonomics=true;xmit_table_msgs_per_row=2000;xmit_table_max_compaction_time=30000;become_server_queue_size=50;xmit_interval=500;print_stability_history_on_failed_xmit=false;resend_last_seqno=true;max_xmit_req_size=511600;discard_delivered_msgs=true;suppress_time_non_member_warnings=60000;max_msg_batch_size=100;xmit_table_num_rows=100;stats=true;xmit_from_random_member=false;log_discard_msgs=true;log_not_found_msgs=true;xmit_table_resize_factor=1.2;name=NAKACK2;id=57;max_rebroadcast_timeout=2000;use_mcast_xmit_req=false)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :UNICAST3(ergonomics=true;xmit_table_msgs_per_row=1000;xmit_table_max_compaction_time=30000;ack_threshold=5;sync_min_interval=2000;max_retransmit_time=60000;xmit_interval=500;max_xmit_req_size=511600;conn_close_timeout=10000;max_msg_batch_size=500;conn_expiry_timeout=120000;ack_batches_immediately=true;xmit_table_num_rows=100;stats=true;xmit_table_resize_factor=1.2;log_not_found_msgs=true;name=UNICAST3;id=64)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :pbcast.STABLE(cap=0.1;stability_delay=0;stats=true;ergonomics=true;name=STABLE;desired_avg_gossip=50000;max_bytes=8000000;id=16;send_stable_msgs_to_coord_only=true)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :pbcast.GMS(max_join_attempts=10;print_local_addr=true;handle_concurrent_startup=true;view_bundling=true;leave_timeout=1000;log_view_warnings=true;install_view_locally_first=true;ergonomics=true;use_delta_views=true;resume_task_timeout=20000;use_flush_if_present=true;print_physical_addrs=true;join_timeout=3000;view_ack_collection_timeout=2000;stats=true;num_prev_views=10;merge_timeout=5000;max_bundling_time=50;name=GMS;num_prev_mbrs=50;id=14;log_collect_msgs=false;membership_change_policy=org.jgroups.protocols.pbcast.GMS$DefaultMembershipPolicy@23ee2ccf)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :MFC(min_threshold=0.4;stats=true;ergonomics=true;max_credits=2000000;name=MFC;min_credits=800000;id=44;max_block_time=500;ignore_synchronous_response=false)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :FRAG2(frag_size=60000;stats=true;ergonomics=true;name=FRAG2;id=5)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :pbcast.STATE_TRANSFER(stats=true;ergonomics=true;name=STATE_TRANSFER;id=17)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :CENTRAL_LOCK(stats=true;ergonomics=true;use_thread_id_for_lock_owner=true;name=CENTRAL_LOCK;id=50;num_backups=1;bypass_bundling=true;lock_striping_size=10)
ehcache-demo-cb44bbf88-nvg4w ehcache-demo :COUNTER(stats=true;ergonomics=true;name=COUNTER;id=53;reconciliation_timeout=10000;timeout=60000;num_backups=1;bypass_bundling=true)
```
